-- Auto-generated: Wikipedia photo URLs for persons
-- Run after initial seed to update main_photo_url

UPDATE persons SET main_photo_url = '/uploads/seed/клеопатра_vii_2fb906.jpg' WHERE name = 'Клеопатра VII' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тутанхамон_001eea.jpg' WHERE name = 'Тутанхамон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/александр_македонский_bc232d.jpg' WHERE name = 'Александр Македонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аристотель_27f82c.jpg' WHERE name = 'Аристотель' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_юлий_цезарь_6ea0c2.jpg' WHERE name = 'Гай Юлий Цезарь' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/чингисхан_9bd4e6.jpg' WHERE name = 'Чингисхан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/леонардо_да_винчи_ab427b.jpg' WHERE name = 'Леонардо да Винчи' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/жанна_дарк_02aa82.jpg' WHERE name = 'Жанна д''Арк' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/наполеон_бонапарт_47ccb6.jpg' WHERE name = 'Наполеон Бонапарт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/александр_сергеевич_пушкин_e2345f.jpg' WHERE name = 'Александр Сергеевич Пушкин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/людвиг_ван_бетховен_67b6f8.jpg' WHERE name = 'Людвиг ван Бетховен' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/альберт_эйнштейн_28356d.jpg' WHERE name = 'Альберт Эйнштейн' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/юрий_алексеевич_гагарин_b17f68.jpg' WHERE name = 'Юрий Алексеевич Гагарин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/никола_тесла_b0f6b4.jpg' WHERE name = 'Никола Тесла' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/махатма_ганди_bade83.jpg' WHERE name = 'Махатма Ганди' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хеопс_de086a.jpg' WHERE name = 'Хеопс' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_ii_685d61.jpg' WHERE name = 'Рамзес II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нефертити_92b117.jpg' WHERE name = 'Нефертити' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/имхотеп_312f5a.jpg' WHERE name = 'Имхотеп' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хатшепсут_8e545a.jpg' WHERE name = 'Хатшепсут' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эхнатон_42b160.jpg' WHERE name = 'Эхнатон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тутмос_iii_d22bc7.jpg' WHERE name = 'Тутмос III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/снофру_d3ce5f.jpg' WHERE name = 'Снофру' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_i_сотер_b1b66d.jpg' WHERE name = 'Птолемей I Сотер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мернептах_cb6741.jpg' WHERE name = 'Мернептах' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сократ_886c4b.jpg' WHERE name = 'Сократ' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/платон_b61614.jpg' WHERE name = 'Платон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гомер_8e342f.jpg' WHERE name = 'Гомер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/геродот_051924.jpg' WHERE name = 'Геродот' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пифагор_02373a.jpg' WHERE name = 'Пифагор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/перикл_cf9850.jpg' WHERE name = 'Перикл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/архимед_008d65.jpg' WHERE name = 'Архимед' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/демокрит_042294.jpg' WHERE name = 'Демокрит' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гиппократ_27493a.jpg' WHERE name = 'Гиппократ' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фидий_05f264.jpg' WHERE name = 'Фидий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ганнибал_барка_7b9aac.jpg' WHERE name = 'Ганнибал Барка' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_аврелий_26e11c.jpg' WHERE name = 'Марк Аврелий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/октавиан_август_c51173.jpg' WHERE name = 'Октавиан Август' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нерон_d3cac8.jpg' WHERE name = 'Нерон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/спартак_e5d663.jpg' WHERE name = 'Спартак' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/цицерон_f2ac47.jpg' WHERE name = 'Цицерон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/евклид_d1d3b5.jpg' WHERE name = 'Евклид' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вергилий_39c888.jpg' WHERE name = 'Вергилий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/овидий_4ac41d.jpg' WHERE name = 'Овидий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сенека_2f7eb3.jpg' WHERE name = 'Сенека' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/диоген_синопский_287b36.jpg' WHERE name = 'Диоген Синопский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ксеркс_i_6daaad.jpg' WHERE name = 'Ксеркс I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фукидид_72b9b9.jpg' WHERE name = 'Фукидид' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эпикур_cd2710.jpg' WHERE name = 'Эпикур' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/софокл_6c3bf9.jpg' WHERE name = 'Софокл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/еврипид_e240a7.jpg' WHERE name = 'Еврипид' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эсхил_d4355d.jpg' WHERE name = 'Эсхил' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/константин_великий_69c66a.jpg' WHERE name = 'Константин Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/траян_967054.jpg' WHERE name = 'Траян' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/плутарх_7bb88e.jpg' WHERE name = 'Плутарх' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_8cde6e.jpg' WHERE name = 'Птолемей' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гален_5d54d3.jpg' WHERE name = 'Гален' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аттила_6d2bd0.jpg' WHERE name = 'Аттила' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/карл_великий_107aaf.jpg' WHERE name = 'Карл Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вильгельм_завоеватель_3f40c2.jpg' WHERE name = 'Вильгельм Завоеватель' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ричард_i_львиное_сердце_60b6bc.jpg' WHERE name = 'Ричард I Львиное Сердце' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/салах_ад-дин_b6e4c5.jpg' WHERE name = 'Салах ад-Дин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марко_поло_c42b79.jpg' WHERE name = 'Марко Поло' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/данте_алигьери_84d863.jpg' WHERE name = 'Данте Алигьери' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фома_аквинский_bb2d84.jpg' WHERE name = 'Фома Аквинский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/франциск_ассизский_4c4306.jpg' WHERE name = 'Франциск Ассизский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/роджер_бэкон_6b4a5c.jpg' WHERE name = 'Роджер Бэкон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тамерлан_8d62dc.jpg' WHERE name = 'Тамерлан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иоганн_гутенберг_646a6c.jpg' WHERE name = 'Иоганн Гутенберг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/авиценна_9f0b90.jpg' WHERE name = 'Авиценна' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аль-хорезми_98c537.jpg' WHERE name = 'Аль-Хорезми' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/омар_хайям_2cda0d.jpg' WHERE name = 'Омар Хайям' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джалаладдин_руми_795215.jpg' WHERE name = 'Джалаладдин Руми' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/владимир_святой_15eb24.jpg' WHERE name = 'Владимир Святой' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ярослав_мудрый_456fe8.jpg' WHERE name = 'Ярослав Мудрый' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/александр_невский_4ded55.jpg' WHERE name = 'Александр Невский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/дмитрий_донской_21eec3.jpg' WHERE name = 'Дмитрий Донской' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джеффри_чосер_d8a66f.jpg' WHERE name = 'Джеффри Чосер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/томас_мор_cd1cbe.jpg' WHERE name = 'Томас Мор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/жанна_де_бар_7bf0b6.jpg' WHERE name = 'Жанна де Бар' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/андрей_рублёв_9dc4f7.jpg' WHERE name = 'Андрей Рублёв' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ибн_баттута_aa0597.jpg' WHERE name = 'Ибн Баттута' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/микеланджело_буонарроти_ca7a30.jpg' WHERE name = 'Микеланджело Буонарроти' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рафаэль_санти_7dea71.jpg' WHERE name = 'Рафаэль Санти' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сандро_боттичелли_a16f41.jpg' WHERE name = 'Сандро Боттичелли' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/николо_макиавелли_268105.jpg' WHERE name = 'Николо Макиавелли' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/христофор_колумб_58b195.jpg' WHERE name = 'Христофор Колумб' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/васко_да_гама_cc6026.jpg' WHERE name = 'Васко да Гама' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фернан_магеллан_90f0bb.jpg' WHERE name = 'Фернан Магеллан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мартин_лютер_87ea90.jpg' WHERE name = 'Мартин Лютер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/николай_коперник_7e7d7b.jpg' WHERE name = 'Николай Коперник' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эразм_роттердамский_624ccc.jpg' WHERE name = 'Эразм Роттердамский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тициан_da1e3c.jpg' WHERE name = 'Тициан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/альбрехт_дюрер_a46427.jpg' WHERE name = 'Альбрехт Дюрер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иван_iii_великий_3fb56b.jpg' WHERE name = 'Иван III Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иван_iv_грозный_c7597e.jpg' WHERE name = 'Иван IV Грозный' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/уильям_шекспир_98e758.jpg' WHERE name = 'Уильям Шекспир' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мигель_де_сервантес_1c1e32.jpg' WHERE name = 'Мигель де Сервантес' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/галилео_галилей_d8621b.jpg' WHERE name = 'Галилео Галилей' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/исаак_ньютон_e15d2a.jpg' WHERE name = 'Исаак Ньютон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иоганн_себастьян_бах_5247ca.jpg' WHERE name = 'Иоганн Себастьян Бах' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вольфганг_амадей_моцарт_d03598.jpg' WHERE name = 'Вольфганг Амадей Моцарт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вольтер_073201.jpg' WHERE name = 'Вольтер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/жан-жак_руссо_a96bf0.jpg' WHERE name = 'Жан-Жак Руссо' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/бенджамин_франклин_567455.jpg' WHERE name = 'Бенджамин Франклин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джордж_вашингтон_524078.jpg' WHERE name = 'Джордж Вашингтон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иммануил_кант_3c9beb.jpg' WHERE name = 'Иммануил Кант' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пётр_i_великий_77d1a8.jpg' WHERE name = 'Пётр I Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/екатерина_ii_великая_20c72f.jpg' WHERE name = 'Екатерина II Великая' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/михаил_васильевич_ломоносов_a3b206.jpg' WHERE name = 'Михаил Васильевич Ломоносов' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/чарльз_дарвин_e0955e.jpg' WHERE name = 'Чарльз Дарвин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/карл_маркс_dcc90d.jpg' WHERE name = 'Карл Маркс' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/авраам_линкольн_ac34f9.jpg' WHERE name = 'Авраам Линкольн' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/лев_николаевич_толстой_36b34d.jpg' WHERE name = 'Лев Николаевич Толстой' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фёдор_михайлович_достоевский_f67b14.jpg' WHERE name = 'Фёдор Михайлович Достоевский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/антон_павлович_чехов_423d5a.jpg' WHERE name = 'Антон Павлович Чехов' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/виктор_гюго_dd0c0c.jpg' WHERE name = 'Виктор Гюго' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рембрандт_ван_рейн_250bcd.jpg' WHERE name = 'Рембрандт ван Рейн' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/александр_суворов_d1ae4d.jpg' WHERE name = 'Александр Суворов' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/михаил_иванович_кутузов_ddc372.jpg' WHERE name = 'Михаил Иванович Кутузов' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/дмитрий_иванович_менделеев_21052e.jpg' WHERE name = 'Дмитрий Иванович Менделеев' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/томас_эдисон_5b72ba.jpg' WHERE name = 'Томас Эдисон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/луи_пастер_06d8a6.jpg' WHERE name = 'Луи Пастер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рихард_вагнер_982f53.jpg' WHERE name = 'Рихард Вагнер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пётр_ильич_чайковский_e27e37.jpg' WHERE name = 'Пётр Ильич Чайковский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/королева_виктория_c48872.jpg' WHERE name = 'Королева Виктория' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/отто_фон_бисмарк_b6d289.jpg' WHERE name = 'Отто фон Бисмарк' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/симон_боливар_5a886b.jpg' WHERE name = 'Симон Боливар' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фридрих_ницше_02af7b.jpg' WHERE name = 'Фридрих Ницше' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мария_кюри_4571b9.jpg' WHERE name = 'Мария Кюри' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/уинстон_черчилль_3be39a.jpg' WHERE name = 'Уинстон Черчилль' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/франклин_рузвельт_1e6738.jpg' WHERE name = 'Франклин Рузвельт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иосиф_виссарионович_сталин_baa5e4.jpg' WHERE name = 'Иосиф Виссарионович Сталин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/владимир_ильич_ленин_11030d.jpg' WHERE name = 'Владимир Ильич Ленин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/георгий_константинович_жуков_ec4678.jpg' WHERE name = 'Георгий Константинович Жуков' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мартин_лютер_кинг_c5710b.jpg' WHERE name = 'Мартин Лютер Кинг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нельсон_мандела_0429e6.jpg' WHERE name = 'Нельсон Мандела' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пабло_пикассо_a4f382.jpg' WHERE name = 'Пабло Пикассо' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сальвадор_дали_aeb880.jpg' WHERE name = 'Сальвадор Дали' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фрида_кало_d188b4.jpg' WHERE name = 'Фрида Кало' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/чарли_чаплин_b7443c.jpg' WHERE name = 'Чарли Чаплин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/зигмунд_фрейд_170637.jpg' WHERE name = 'Зигмунд Фрейд' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/макс_планк_4f47d1.jpg' WHERE name = 'Макс Планк' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нильс_бор_175155.jpg' WHERE name = 'Нильс Бор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вернер_гейзенберг_55b018.jpg' WHERE name = 'Вернер Гейзенберг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эрвин_шрёдингер_7490a5.jpg' WHERE name = 'Эрвин Шрёдингер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сергей_павлович_королёв_7770c7.jpg' WHERE name = 'Сергей Павлович Королёв' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/игорь_васильевич_курчатов_52159f.jpg' WHERE name = 'Игорь Васильевич Курчатов' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/андрей_дмитриевич_сахаров_b841c4.jpg' WHERE name = 'Андрей Дмитриевич Сахаров' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/дмитрий_дмитриевич_шостакович_6eed2c.jpg' WHERE name = 'Дмитрий Дмитриевич Шостакович' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эрнест_хемингуэй_4bce60.jpg' WHERE name = 'Эрнест Хемингуэй' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/габриэль_гарсиа_маркес_1da110.jpg' WHERE name = 'Габриэль Гарсиа Маркес' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мао_цзэдун_59eec2.jpg' WHERE name = 'Мао Цзэдун' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/индира_ганди_fb9e8d.jpg' WHERE name = 'Индира Ганди' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/стивен_хокинг_22b97a.jpg' WHERE name = 'Стивен Хокинг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мать_тереза_9664ec.jpg' WHERE name = 'Мать Тереза' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сергей_михайлович_эйзенштейн_2a692c.jpg' WHERE name = 'Сергей Михайлович Эйзенштейн' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/коко_шанель_a9488b.jpg' WHERE name = 'Коко Шанель' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/че_гевара_166798.jpg' WHERE name = 'Че Гевара' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/михаил_афанасьевич_булгаков_b506f1.jpg' WHERE name = 'Михаил Афанасьевич Булгаков' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/алан_тьюринг_41a7d5.jpg' WHERE name = 'Алан Тьюринг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/александр_флеминг_77b4ca.jpg' WHERE name = 'Александр Флеминг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/амелия_эрхарт_99e742.jpg' WHERE name = 'Амелия Эрхарт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/энрико_ферми_74a555.jpg' WHERE name = 'Энрико Ферми' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джон_фон_нейман_c8180c.jpg' WHERE name = 'Джон Фон Нейман' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/роберт_оппенгеймер_632aa3.jpg' WHERE name = 'Роберт Оппенгеймер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/валентина_терешкова_b00bed.jpg' WHERE name = 'Валентина Терешкова' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/борис_леонидович_пастернак_87338c.jpg' WHERE name = 'Борис Леонидович Пастернак' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/анна_андреевна_ахматова_302e93.jpg' WHERE name = 'Анна Андреевна Ахматова' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/владимир_владимирович_маяковский_8ad4b4.jpg' WHERE name = 'Владимир Владимирович Маяковский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/вернер_фон_браун_8fd949.jpg' WHERE name = 'Вернер фон Браун' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нил_армстронг_5ad985.jpg' WHERE name = 'Нил Армстронг' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/михаил_сергеевич_горбачёв_6f4f57.jpg' WHERE name = 'Михаил Сергеевич Горбачёв' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нармер_менес_ed512d.jpg' WHERE name = 'Нармер (Менес)' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джер_baf24a.jpg' WHERE name = 'Джер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ден_983210.jpg' WHERE name = 'Ден' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хасехемуи_19d8ec.jpg' WHERE name = 'Хасехемуи' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джосер_143398.jpg' WHERE name = 'Джосер' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хуни_3044ee.jpg' WHERE name = 'Хуни' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/джедефра_0b35b0.jpg' WHERE name = 'Джедефра' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хафра_e4e94b.jpg' WHERE name = 'Хафра' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/менкаура_7ab82e.jpg' WHERE name = 'Менкаура' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/усеркаф_769873.jpg' WHERE name = 'Усеркаф' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сахура_de09b4.jpg' WHERE name = 'Сахура' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нефериркара_какаи_bbc9de.jpg' WHERE name = 'Нефериркара Какаи' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/униc_1a38fa.jpg' WHERE name = 'Униc' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пепи_i_166729.jpg' WHERE name = 'Пепи I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пепи_ii_79cdeb.jpg' WHERE name = 'Пепи II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ментухотеп_ii_8137ca.jpg' WHERE name = 'Ментухотеп II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ментухотеп_iii_217259.jpg' WHERE name = 'Ментухотеп III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменемхет_i_8d69d5.jpg' WHERE name = 'Аменемхет I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сенусерт_i_76e544.jpg' WHERE name = 'Сенусерт I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменемхет_ii_a47001.jpg' WHERE name = 'Аменемхет II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сенусерт_ii_aa8393.jpg' WHERE name = 'Сенусерт II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сенусерт_iii_c54e20.jpg' WHERE name = 'Сенусерт III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменемхет_iii_576071.jpg' WHERE name = 'Аменемхет III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/собекнефру_390d0e.jpg' WHERE name = 'Собекнефру' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/яхмос_i_eb58b9.jpg' WHERE name = 'Яхмос I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменхотеп_i_448aa1.jpg' WHERE name = 'Аменхотеп I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тутмос_i_6859be.jpg' WHERE name = 'Тутмос I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тутмос_ii_68f025.jpg' WHERE name = 'Тутмос II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменхотеп_ii_ff8934.jpg' WHERE name = 'Аменхотеп II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тутмос_iv_a9230d.jpg' WHERE name = 'Тутмос IV' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аменхотеп_iii_665e57.jpg' WHERE name = 'Аменхотеп III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сменхкара_e433ed.jpg' WHERE name = 'Сменхкара' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эйе_40513c.jpg' WHERE name = 'Эйе' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хоремхеб_2dda45.jpg' WHERE name = 'Хоремхеб' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_i_a60ce7.jpg' WHERE name = 'Рамзес I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сети_i_43fe9c.jpg' WHERE name = 'Сети I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сети_ii_96dffb.jpg' WHERE name = 'Сети II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/таусерт_6d9e04.jpg' WHERE name = 'Таусерт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сетнахт_986e52.jpg' WHERE name = 'Сетнахт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_iii_483da7.jpg' WHERE name = 'Рамзес III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_iv_ee0d21.jpg' WHERE name = 'Рамзес IV' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_vi_17f017.jpg' WHERE name = 'Рамзес VI' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_ix_9132d4.jpg' WHERE name = 'Рамзес IX' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/рамзес_xi_0a6dda.jpg' WHERE name = 'Рамзес XI' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/псусеннес_i_0baf54.jpg' WHERE name = 'Псусеннес I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/шешонк_i_de664e.jpg' WHERE name = 'Шешонк I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пианхи_пийе_3b7de8.jpg' WHERE name = 'Пианхи (Пийе)' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тахарка_4f69ee.jpg' WHERE name = 'Тахарка' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/псамметих_i_a9d7cc.jpg' WHERE name = 'Псамметих I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нехо_ii_191a00.jpg' WHERE name = 'Нехо II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/амасис_ii_f79796.jpg' WHERE name = 'Амасис II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нектанеб_i_1fe875.jpg' WHERE name = 'Нектанеб I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/нектанеб_ii_39ac0e.jpg' WHERE name = 'Нектанеб II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_ii_филадельф_bac47f.jpg' WHERE name = 'Птолемей II Филадельф' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_iii_эвергет_f65395.jpg' WHERE name = 'Птолемей III Эвергет' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_iv_филопатор_60daf3.jpg' WHERE name = 'Птолемей IV Филопатор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_v_эпифан_4938ef.jpg' WHERE name = 'Птолемей V Эпифан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/птолемей_xii_авлет_c46820.jpg' WHERE name = 'Птолемей XII Авлет' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фалес_милетский_288d61.jpg' WHERE name = 'Фалес Милетский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/анаксимандр_милетский_ed249e.jpg' WHERE name = 'Анаксимандр Милетский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/анаксимен_милетский_0d23ff.jpg' WHERE name = 'Анаксимен Милетский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гераклит_эфесский_c0e2e8.jpg' WHERE name = 'Гераклит Эфесский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/парменид_элейский_301943.jpg' WHERE name = 'Парменид Элейский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ксенофан_колофонский_c73855.jpg' WHERE name = 'Ксенофан Колофонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гесиод_0f9432.jpg' WHERE name = 'Гесиод' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сапфо_2a51bd.jpg' WHERE name = 'Сапфо' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пиндар_0a08f6.jpg' WHERE name = 'Пиндар' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/анакреонт_14c27c.jpg' WHERE name = 'Анакреонт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/архилох_89665f.jpg' WHERE name = 'Архилох' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/симонид_кеосский_c5cec5.jpg' WHERE name = 'Симонид Кеосский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/солон_9a5ae3.jpg' WHERE name = 'Солон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/писистрат_20b9ef.jpg' WHERE name = 'Писистрат' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/клисфен_7d8dc9.jpg' WHERE name = 'Клисфен' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/поликрат_самосский_9be626.jpg' WHERE name = 'Поликрат Самосский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/крез_6187f8.jpg' WHERE name = 'Крез' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мильтиад_f5eb68.jpg' WHERE name = 'Мильтиад' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фемистокл_6c248c.jpg' WHERE name = 'Фемистокл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/анаксагор_50b993.jpg' WHERE name = 'Анаксагор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/протагор_e35eff.jpg' WHERE name = 'Протагор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/зенон_элейский_01ea47.jpg' WHERE name = 'Зенон Элейский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эмпедокл_ceacf0.jpg' WHERE name = 'Эмпедокл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/антисфен_a8d9bb.jpg' WHERE name = 'Антисфен' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/теофраст_e0ff78.jpg' WHERE name = 'Теофраст' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/демосфен_03f434.jpg' WHERE name = 'Демосфен' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/исократ_7c7db3.jpg' WHERE name = 'Исократ' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/алкивиад_402613.jpg' WHERE name = 'Алкивиад' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/кимон_4b6dd6.jpg' WHERE name = 'Кимон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эпаминонд_514590.jpg' WHERE name = 'Эпаминонд' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/агесилай_ii_44c92e.jpg' WHERE name = 'Агесилай II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/лисандр_5b70f1.jpg' WHERE name = 'Лисандр' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/филипп_ii_македонский_cc156a.jpg' WHERE name = 'Филипп II Македонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аристофан_7e579e.jpg' WHERE name = 'Аристофан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ксенофонт_ab81da.jpg' WHERE name = 'Ксенофонт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/поликлет_8df3b2.jpg' WHERE name = 'Поликлет' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/пракситель_074c2c.jpg' WHERE name = 'Пракситель' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/скопас_7cab9f.jpg' WHERE name = 'Скопас' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/апеллес_f77d1b.jpg' WHERE name = 'Апеллес' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/герофил_халкедонский_88d0cd.jpg' WHERE name = 'Герофил Халкедонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/селевк_i_никатор_88dfcf.jpg' WHERE name = 'Селевк I Никатор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/антигон_i_одноглазый_bca742.jpg' WHERE name = 'Антигон I Одноглазый' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/деметрий_i_полиоркет_2d158b.jpg' WHERE name = 'Деметрий I Полиоркет' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/антиох_iii_великий_038a31.jpg' WHERE name = 'Антиох III Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/митридат_vi_евпатор_dbcd5c.jpg' WHERE name = 'Митридат VI Евпатор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/зенон_китийский_5a63f5.jpg' WHERE name = 'Зенон Китийский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/хрисипп_638fe6.jpg' WHERE name = 'Хрисипп' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/карнеад_fa68d7.jpg' WHERE name = 'Карнеад' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/посидоний_7e6bad.jpg' WHERE name = 'Посидоний' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эратосфен_85eff4.jpg' WHERE name = 'Эратосфен' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аристарх_самосский_28dffc.jpg' WHERE name = 'Аристарх Самосский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аполлоний_пергский_da851d.jpg' WHERE name = 'Аполлоний Пергский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гиппарх_3645e7.jpg' WHERE name = 'Гиппарх' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ктесибий_4855e9.jpg' WHERE name = 'Ктесибий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/полибий_1a781d.jpg' WHERE name = 'Полибий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/феокрит_40a34b.jpg' WHERE name = 'Феокрит' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аполлоний_родосский_b071af.jpg' WHERE name = 'Аполлоний Родосский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сципион_африканский_ebdb45.jpg' WHERE name = 'Сципион Африканский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_марий_ca7ae7.jpg' WHERE name = 'Гай Марий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/луций_корнелий_сулла_106e5f.jpg' WHERE name = 'Луций Корнелий Сулла' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гней_помпей_великий_d4691f.jpg' WHERE name = 'Гней Помпей Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_лициний_красс_2a8fd7.jpg' WHERE name = 'Марк Лициний Красс' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_антоний_e2231d.jpg' WHERE name = 'Марк Антоний' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/фабий_максим_кунктатор_ace486.jpg' WHERE name = 'Фабий Максим Кунктатор' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/катон_старший_eb3a55.jpg' WHERE name = 'Катон Старший' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тиберий_гракх_ea969b.jpg' WHERE name = 'Тиберий Гракх' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_гракх_533ac9.jpg' WHERE name = 'Гай Гракх' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/катон_младший_1aa89c.jpg' WHERE name = 'Катон Младший' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_юний_брут_78fd6a.jpg' WHERE name = 'Марк Юний Брут' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тит_лукреций_кар_6de459.jpg' WHERE name = 'Тит Лукреций Кар' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_валерий_катулл_c6e79e.jpg' WHERE name = 'Гай Валерий Катулл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_саллюстий_крисп_883122.jpg' WHERE name = 'Гай Саллюстий Крисп' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_теренций_варрон_4271c0.jpg' WHERE name = 'Марк Теренций Варрон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тит_макций_плавт_49679e.jpg' WHERE name = 'Тит Макций Плавт' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/публий_теренций_афр_deaab0.jpg' WHERE name = 'Публий Теренций Афр' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тиберий_870c53.jpg' WHERE name = 'Тиберий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/калигула_9e4107.jpg' WHERE name = 'Калигула' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/клавдий_77719a.jpg' WHERE name = 'Клавдий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/веспасиан_324286.jpg' WHERE name = 'Веспасиан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/домициан_076a7f.jpg' WHERE name = 'Домициан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/адриан_4cb95a.jpg' WHERE name = 'Адриан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/антонин_пий_856473.jpg' WHERE name = 'Антонин Пий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/коммод_95b6ba.jpg' WHERE name = 'Коммод' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/септимий_север_f5e089.jpg' WHERE name = 'Септимий Север' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/диоклетиан_c320e4.jpg' WHERE name = 'Диоклетиан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/юлиан_отступник_d832c2.jpg' WHERE name = 'Юлиан Отступник' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/феодосий_i_великий_0f8633.jpg' WHERE name = 'Феодосий I Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ромул_августул_7c449c.jpg' WHERE name = 'Ромул Августул' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/тит_ливий_d61485.jpg' WHERE name = 'Тит Ливий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/публий_корнелий_тацит_696ed5.jpg' WHERE name = 'Публий Корнелий Тацит' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гай_светоний_транквилл_c783d4.jpg' WHERE name = 'Гай Светоний Транквилл' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/квинт_гораций_флакк_2809f5.jpg' WHERE name = 'Квинт Гораций Флакк' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/децим_юний_ювенал_ac49cb.jpg' WHERE name = 'Децим Юний Ювенал' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_валерий_марциал_ea3604.jpg' WHERE name = 'Марк Валерий Марциал' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_анней_лукан_0cf952.jpg' WHERE name = 'Марк Анней Лукан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/апулей_4454f8.jpg' WHERE name = 'Апулей' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/плиний_младший_47ae62.jpg' WHERE name = 'Плиний Младший' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аммиан_марцеллин_e5d907.jpg' WHERE name = 'Аммиан Марцеллин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/страбон_a03d94.jpg' WHERE name = 'Страбон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/диодор_сицилийский_b6021c.jpg' WHERE name = 'Диодор Сицилийский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/флавий_арриан_502def.jpg' WHERE name = 'Флавий Арриан' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/эпиктет_5bc7f7.jpg' WHERE name = 'Эпиктет' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/плотин_cd2257.jpg' WHERE name = 'Плотин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/плиний_старший_6c1069.jpg' WHERE name = 'Плиний Старший' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/герон_александрийский_75addd.jpg' WHERE name = 'Герон Александрийский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/витрувий_94b97d.jpg' WHERE name = 'Витрувий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/секст_юлий_фронтин_a1b119.jpg' WHERE name = 'Секст Юлий Фронтин' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/педаний_диоскорид_eb0895.jpg' WHERE name = 'Педаний Диоскорид' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/марк_випсаний_агриппа_2796c0.jpg' WHERE name = 'Марк Випсаний Агриппа' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/германик_94f1b9.jpg' WHERE name = 'Германик' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/флавий_аэций_bce2e6.jpg' WHERE name = 'Флавий Аэций' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/стилихон_ba0ae3.jpg' WHERE name = 'Стилихон' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иисус_христос_6e93c2.jpg' WHERE name = 'Иисус Христос' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/апостол_павел_0f335c.jpg' WHERE name = 'Апостол Павел' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/апостол_пётр_807a5b.jpg' WHERE name = 'Апостол Пётр' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/августин_блаженный_54aaa1.jpg' WHERE name = 'Августин Блаженный' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иероним_стридонский_bca0b8.jpg' WHERE name = 'Иероним Стридонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иоанн_златоуст_cf8ff8.jpg' WHERE name = 'Иоанн Златоуст' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ориген_ec583a.jpg' WHERE name = 'Ориген' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/кир_ii_великий_a6364f.jpg' WHERE name = 'Кир II Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/дарий_i_великий_f66824.jpg' WHERE name = 'Дарий I Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/дарий_iii_ee52c7.jpg' WHERE name = 'Дарий III' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/артаксеркс_i_ee8929.jpg' WHERE name = 'Артаксеркс I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/шапур_i_e126ea.jpg' WHERE name = 'Шапур I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/будда_8fc40d.jpg' WHERE name = 'Будда' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/конфуций_ee9e26.jpg' WHERE name = 'Конфуций' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/лао-цзы_f413a8.jpg' WHERE name = 'Лао-цзы' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сунь-цзы_947ead.jpg' WHERE name = 'Сунь-цзы' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мэн-цзы_a90769.jpg' WHERE name = 'Мэн-цзы' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/чжуан-цзы_77ac54.jpg' WHERE name = 'Чжуан-цзы' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/мо-цзы_7159c4.jpg' WHERE name = 'Мо-цзы' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/цинь_шихуанди_d23e39.jpg' WHERE name = 'Цинь Шихуанди' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/сыма_цянь_659cff.jpg' WHERE name = 'Сыма Цянь' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ашока_938a19.jpg' WHERE name = 'Ашока' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/чандрагупта_маурья_42f723.jpg' WHERE name = 'Чандрагупта Маурья' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/каутилья_2d1b0b.jpg' WHERE name = 'Каутилья' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/панини_ffbbad.jpg' WHERE name = 'Панини' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гамилькар_барка_98df04.jpg' WHERE name = 'Гамилькар Барка' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гасдрубал_барка_7fd652.jpg' WHERE name = 'Гасдрубал Барка' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/масинисса_92d56b.jpg' WHERE name = 'Масинисса' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/югурта_3fe6aa.jpg' WHERE name = 'Югурта' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/верцингеторикс_258a25.jpg' WHERE name = 'Верцингеторикс' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/боудикка_b60f9b.jpg' WHERE name = 'Боудикка' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/арминий_ed2fca.jpg' WHERE name = 'Арминий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/зенобия_de4957.jpg' WHERE name = 'Зенобия' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аларих_i_4d71f8.jpg' WHERE name = 'Аларих I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ирод_великий_ad8b1f.jpg' WHERE name = 'Ирод Великий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иуда_маккавей_1a66c9.jpg' WHERE name = 'Иуда Маккавей' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/иосиф_флавий_616384.jpg' WHERE name = 'Иосиф Флавий' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/филон_александрийский_a755f9.jpg' WHERE name = 'Филон Александрийский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/навуходоносор_ii_fb8441.jpg' WHERE name = 'Навуходоносор II' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/аспасия_e4da6a.jpg' WHERE name = 'Аспасия' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/гипатия_96a650.jpg' WHERE name = 'Гипатия' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/артемисия_i_856217.jpg' WHERE name = 'Артемисия I' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/олимпиада_эпирская_846c8c.jpg' WHERE name = 'Олимпиада Эпирская' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/корнелия_4f27f6.jpg' WHERE name = 'Корнелия' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/агриппина_младшая_a628a3.jpg' WHERE name = 'Агриппина Младшая' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/ливия_друзилла_2d10ce.jpg' WHERE name = 'Ливия Друзилла' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/милон_кротонский_8baa31.jpg' WHERE name = 'Милон Кротонский' AND main_photo_url = '/uploads/seed/default.jpg';
UPDATE persons SET main_photo_url = '/uploads/seed/диагор_родосский_b9e832.jpg' WHERE name = 'Диагор Родосский' AND main_photo_url = '/uploads/seed/default.jpg';
